from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Keep Chrome browser open after program finishes
chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option("detach", True)

driver = webdriver.Chrome(options=chrome_options)
# driver.get(url="https://www.linkedin.com/jobs/search/?currentJobId=3759201692&f_AL=true&geoId=105359710&keywords=Python%20Developer&location=Hatfield%2C%20England%2C%20United%20Kingdom&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true")
driver.get(url="https://www.linkedin.com/jobs/search/?currentJobId=3660142320&f_AL=true&geoId=105359710&keywords=python%20developer&location=Hatfield%2C%20England%2C%20United%20Kingdom&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true")
sign_in = driver.find_element(By.XPATH, value="/html/body/div[1]/header/nav/div/a[2]")
sign_in.click()
email = driver.find_element(By.NAME, value="session_key")
password = driver.find_element(By.NAME, value="session_password")
after_details = driver.find_element(By.XPATH, value='//*[@id="organic-div"]/form/div[3]/button')
email.send_keys("MY EMAIL")
# email.send_keys("MY EMAIL")
password.send_keys("MY PASSWORD")
after_details.click()
time.sleep(10)
# verify_form = driver.find_element(By.NAME, value="pin")
# verify_submit = driver.find_element(By.XPATH, value='//*[@id="email-pin-submit-button"]')
# verify_form.send_keys(input("Enter the verification code: "))
# verify_submit.click()

# Easy Apply
# python_job = driver.find_element(By.XPATH, value='//*[@id="ember192"]')
# python_job.click()
solve_captcha = input("Have you solved captcha: ")
linked_list = driver.find_elements(By.CSS_SELECTOR, value=".disabled.ember-view.job-card-container__link.job-card-list__title")
texts = [x.text for x in linked_list]
print(texts)
job_text = driver.find_element(By.LINK_TEXT, value=texts[2])
job_text.click()
# linked_text.click()
# easy_apply = driver.find_element(By.CSS_SELECTOR, value='.jobs-apply-button--top-card button')
# print(easy_apply.text)
time.sleep(5)
save_job = driver.find_element(By.XPATH, value='/html/body/div[5]/div[3]/div[4]/div/div/main/div/div[2]/div/div[2]/div/div[1]/div/div[1]/div/div[1]/div[1]/div[4]/div/button')
save_job.click()
print("Saved...")
# easy_apply.click()
# driver.quit()
# phone_number = driver.find_element(By.XPATH, value='/html/body/div[3]/div/div/div[2]/div/div[2]/form/div/div/div[5]/div/div/div[1]/div/input')
# phone_number.send_keys("09060630130")
# next_button = driver.find_element(By.XPATH, value="/html/body/div[3]/div/div/div[2]/div/div[2]/form/footer/div[2]/button")
# next_button.click()
# time.sleep(3)
# another_next = driver.find_element(By.XPATH, value="/html/body/div[3]/div/div/div[2]/div/div[2]/form/footer/div[2]/button[2]")
# another_next.click()
# time.sleep(3)
# next_next = driver.find_element(By.XPATH, value="/html/body/div[3]/div/div/div[2]/div/div[2]/form/footer/div[2]/button[2]")
# next_next.click()
# time.sleep(3)
# review_button = driver.find_element(By.XPATH, value="/html/body/div[3]/div/div/div[2]/div/div[2]/form/footer/div[2]/button[2]")
# review_button.click()
# time.sleep(3)
# submit_app = driver.find_element(By.XPATH, value="/html/body/div[3]/div/div/div[2]/div/div[2]/div/footer/div[3]/button[2]")
# submit_app.click()
# driver.quit()